// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/csv-import/CsvImportPreview.tsx": () => import("../components/mockups/csv-import/CsvImportPreview.tsx"),
  "./components/mockups/csv-import/CsvImportUpload.tsx": () => import("../components/mockups/csv-import/CsvImportUpload.tsx")
};
