#!/bin/bash
set -e
# Remove any pnpm-lock.yaml regenerated by task agents
rm -f pnpm-lock.yaml
node -e "require('child_process').execSync('npm install', {stdio: 'inherit', timeout: 120000})"
npm run -w @workspace/db push
