import { shadcn } from '@clerk/themes'

export const clerkAppearance = {
  theme: shadcn,
  cssLayerName: 'clerk',
  variables: {
    colorPrimary: 'hsl(135 100% 50%)',
    colorForeground: 'hsl(0 0% 98%)',
    colorMutedForeground: 'hsl(0 0% 65%)',
    colorDanger: 'hsl(0 84% 60%)',
    colorBackground: 'hsl(0 0% 7%)',
    colorInput: 'hsl(0 0% 15%)',
    colorInputForeground: 'hsl(0 0% 98%)',
    colorNeutral: 'hsl(0 0% 15%)',
    fontFamily: "'Inter', sans-serif",
    borderRadius: '0.25rem',
  },
  elements: {
    rootBox: 'w-full flex justify-center',
    cardBox: 'bg-card rounded-md border border-border w-[440px] max-w-full overflow-hidden shadow-xl',
    card: '!shadow-none !border-0 !bg-transparent !rounded-none',
    footer: '!shadow-none !border-0 !bg-transparent !rounded-none',
    headerTitle: 'text-foreground font-bold text-xl',
    headerSubtitle: 'text-muted-foreground',
    socialButtonsBlockButtonText: { color: 'hsl(0 0% 98%)', fontWeight: '500' },
    formFieldLabel: 'text-foreground font-medium',
    footerActionLink: 'text-primary hover:text-primary/80',
    footerActionText: 'text-muted-foreground',
    dividerText: 'text-muted-foreground',
    identityPreviewEditButton: 'text-primary hover:text-primary/80',
    formFieldSuccessText: 'text-primary',
    alertText: 'text-foreground',
    logoBox: 'flex justify-center mb-4',
    socialButtonsBlockButton: 'bg-muted border border-border hover:bg-accent text-foreground',
    formButtonPrimary: 'bg-primary text-primary-foreground hover:bg-primary/90 font-bold',
    formFieldInput: 'bg-input border-border text-foreground focus:border-primary focus:ring-1 focus:ring-primary',
    footerAction: 'mt-4',
    dividerLine: 'bg-border',
    alert: 'bg-destructive/10 border border-destructive text-destructive',
    otpCodeFieldInput: 'bg-input border-border text-foreground',
    formFieldRow: 'mb-4',
    main: 'w-full',
  },
}
